// <auto-generated />
using System;
using LibrarySystemWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibrarySystemWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119145158_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("LibrarySystemWebAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BorrowCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChartBorderColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChartColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CopiesAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Colour Man",
                            BorrowCount = 0,
                            ChartBorderColor = "#C74422",
                            ChartColor = "#FF5733",
                            CopiesAvailable = 5,
                            ISBN = "9780743273565",
                            Title = "Yellow"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Colour Man",
                            BorrowCount = 0,
                            ChartBorderColor = "#22C788",
                            ChartColor = "#33FFAA",
                            CopiesAvailable = 3,
                            ISBN = "9780743273501",
                            Title = "Orange"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Colour Man",
                            BorrowCount = 0,
                            ChartBorderColor = "#2260C7",
                            ChartColor = "#3385FF",
                            CopiesAvailable = 8,
                            ISBN = "9780743273200",
                            Title = "Green"
                        },
                        new
                        {
                            Id = 4,
                            Author = "F. Scott Fitzgerald",
                            BorrowCount = 0,
                            ChartBorderColor = "#CC6F33",
                            ChartColor = "#FF8C42",
                            CopiesAvailable = 7,
                            ISBN = "9780743273309",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Some Guy",
                            BorrowCount = 0,
                            ChartBorderColor = "#5246A1",
                            ChartColor = "#6A5ACD",
                            CopiesAvailable = 5,
                            ISBN = "9780743273624",
                            Title = "Clean Code"
                        });
                });

            modelBuilder.Entity("LibrarySystemWebAPI.Models.BookLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookLoans");
                });

            modelBuilder.Entity("LibrarySystemWebAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LibrarySystemWebAPI.Models.BookLoan", b =>
                {
                    b.HasOne("LibrarySystemWebAPI.Models.Book", "Book")
                        .WithMany("BookLoans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibrarySystemWebAPI.Models.User", "User")
                        .WithMany("BookLoans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibrarySystemWebAPI.Models.Book", b =>
                {
                    b.Navigation("BookLoans");
                });

            modelBuilder.Entity("LibrarySystemWebAPI.Models.User", b =>
                {
                    b.Navigation("BookLoans");
                });
#pragma warning restore 612, 618
        }
    }
}
